server.port=8085
spring.application.name=auth-service

# Database Setup
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Strategy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka Registry Location
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


# Increase Eureka Client connection and read timeouts (values in milliseconds)
eureka.client.eureka-server-connect-timeout-seconds=10
eureka.client.eureka-server-read-timeout-seconds=10
