server.port=8086
spring.application.name=notification-service

# Eureka Setup
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Kafka Consumer Configurations
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Increase Eureka Client connection and read timeouts (values in milliseconds)
eureka.client.eureka-server-connect-timeout-seconds=10
eureka.client.eureka-server-read-timeout-seconds=10

