server.port=8083
spring.application.name=order-service

# Database Setup
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_order?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Strategy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/


# Kafka Producer Properties
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


# Force Netty to use standard JVM system DNS resolution instead of reactive internet DNS lookup
spring.cloud.gateway.dns-notifier.enabled=false
# If using standard Netty under the hood for WebClient
spring.netty.leak-detection=simple

spring.cloud.loadbalancer.ribbon.enabled=false

# Fixes NXDOMAIN by forcing the load balancer to look at Eureka first
spring.cloud.loadbalancer.zone=default
spring.cloud.loadbalancer.cache.enabled=true
